# Generated by Django 5.1.3 on 2024-11-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.TextField()),
                ('playlists', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
