# Generated by Django 5.1.3 on 2024-11-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_search_delete_coresearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='emotions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='playlists',
            field=models.TextField(),
        ),
    ]
